[build]
  functions = "netlify/functions"
  publish = "public"

[dev]
  functions = "netlify/functions"
  publish = "public"
  port = 8888

# Redirect /api to the simple Netlify function
[[redirects]]
  from = "/api"
  to = "/.netlify/functions/api-simple"
  status = 200

# Redirect /api/* to the simple Netlify function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api-simple"
  status = 200 